version: "3.4"

services:
  spotifydwapi:
    image: spotifydwapi
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MASHINE: ${MASHINE}
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data:rw
  caddy:
    image: caddy:2-alpine
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/public:/app/frontend/public:ro
      - ./frontend/dist:/app/frontend/dist:ro
