services:
  dwman:
    image: dwman
    container_name: dwman
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data:rw
  caddy:
    image: caddy:2-alpine
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data:rw
      - ./caddy_config:/config:rw
