version: "3"

output: "prefixed"

tasks:
  caddy-dev:
    desc: Run Caddy server with dev configuration
    cmds:
      - caddy run --config ./caddy/dev/Caddyfile --adapter caddyfile

  caddy-frontend-dev:
    desc: Run Caddy server with fromtend dev configuration
    cmds:
      - caddy run --config ./caddy/dev/Caddyfile.frontend  --adapter caddyfile

  pnpm-install:
    interactive: true
    desc: Install pnpm dependencies
    dir: '{{ .EXEC_DIR| default "src/frontend" }}'
    cmds:
      - pnpm i
    preconditions:
      - sh: type pnpm

  frontend-dev-internal:
    desc: Start frontend development server
    internal: true
    env:
      VITE_API_URL: "{{ .VITE_API_URL }}"
    dir: src/frontend
    deps:
      - pnpm-install
    interactive: true
    cmds:
      - pnpm run dev

  frontend-dev:
    cmds:
      - task: frontend-dev-internal
        vars:
          VITE_API_URL: "https://test-dwman.akorz-sw1.duckdns.org"

  frontend-api-dev:
    cmds:
      - task: frontend-dev-internal
        vars:
          VITE_API_URL: "https://api.test-dwman.localhost"

  debug-web:
    aliases:
      - dw
    desc: Run vite dev server and local reverse proxy from web
    deps:
      - caddy-frontend-dev
      - frontend-dev
    cmds:
      - echo "Debug session ended"

  debug-backend:
    interactive: true
    aliases:
      - db
    desc: Start Python backend application
    env:
      LOG_LEVEL: ERROR
    cmds:
      - poetry run uvicorn run:app --reload --log-level error --no-access-log

  debug-full:
    aliases:
      - df
    desc: Run fromtend and backend w/ reverse proxy locally
    deps:
      - caddy-dev
      - frontend-api-dev
      - debug-backend

  debug-full-no-back:
    aliases:
      - dfn
    desc: Run fromtend w/o backend w/ reverse proxy locally
    deps:
      - caddy-dev
      - frontend-api-dev

  build-web:
    interactive: true
    aliases:
      - bw
    desc: Build frontend application
    dir: src/frontend
    deps:
      - pnpm-install
    cmds:
      - pnpm run build

  test-backend:
    aliases:
      - tb
    desc: Run backend tests
    interactive: true
    cmd: pytest . -vv

  test-frontend:
    aliases:
      - tf
    desc: Run frontend tests
    interactive: true
    deps:
      - task: pnpm-install
        vars:
          EXEC_DIR: tests/frontend
    dir: tests/frontend
    cmd: pnpm run test-unit

  test-all:
    aliases:
      - ta
    desc: Run all tests
    deps:
      - test-backend
      - test-frontend
    cmd: echo Finished runnig tests

  test-frontend-watch:
    aliases:
      - tw
      - tfw
    desc: Run frontend tests in watch mode
    interactive: true
    deps:
      - task: pnpm-install
        vars:
          EXEC_DIR: tests/frontend
    dir: tests/frontend
    cmd: pnpm run test-unit-watch

  # test-react-frontend:
  #   preconditions:
  #     - sh: pnpm i
  #   interactive: true
  #   dir: tests/frontend
  #   cmd: pnpm run test-ct
