services:
  dwman:
    image: akorzunin/dwman:master
    container_name: dwman
    ports:
      - ${PORT:-8000}:8000
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data:rw
    labels:
      org.opencontainers.group: "logging"
