name: ansible-deploy
description: deploy w/ ansible

runs:
  using: "composite"
  steps:
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yml
        directory: deploy/${{ inputs.deploy_type }}
        configuration: |
          [defaults]
          callbacks_enabled = ansible.posix.profile_tasks, ansible.posix.timer
          stdout_callback = yaml
          nocows = false
          interpreter_python = /usr/bin/python
          [ssh_connection]
          retries=5
        vault_password: ${{ secrets.ANSIBLE_PASS }}
        inventory: ${{ vars.ANSIBLE_HOSTS }}
        options: |
          --inventory .hosts
          --limit ${{ vars.SERVER_GROUP }}
          --verbose
          --extra-vars "
          SPOTIPY_CLIENT_ID=${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET=${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URL=${{ vars.SPOTIPY_REDIRECT_URL }}
          MAIL_USERNAME=${{ vars.MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM=${{ vars.MAIL_FROM }}
          API_LOGIN=${{ vars.API_LOGIN }}
          API_PASSWORD=${{ vars.API_PASSWORD }}
          PORT=${{ vars.PORT }}
          "
