services:
  dwman:
    image: akorzunin/dwman:test
    container_name: dwman
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data:rw
