- name: Deploy dwman to test
  hosts: all
  become: false
  vars:
    project_dir: ~/Documents/dwman-test/

  tasks:
    - name: Copy files for deploy
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ project_dir }}"
        mode: "0644"
        backup: true
      loop:
        - .env
        - compose.yml

    - name: Pull new version of image
      ansible.builtin.command:
        cmd: docker compose -f compose.yml pull
        chdir: "{{ project_dir }}"
      register: out
      changed_when: out.rc != 0

    - name: Deploy dwman-test
      ansible.builtin.command:
        cmd: docker compose -f compose.yml up -d
        chdir: "{{ project_dir }}"
      register: out
      changed_when: out.rc != 0

    - name: Remove old version of image
      ansible.builtin.command:
        cmd: docker image prune --filter="dangling=true" --force
      register: out
      changed_when: out.rc != 0
