name: ci-workflow

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
      - test
  workflow_dispatch:

jobs:
  checks:
    name: run pre-commit hooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install prettier plugins
        run: npm install -D prettier prettier-plugin-tailwindcss
      - uses: pre-commit/action@v3.0.1

  tests-unit-frontend:
    name: run unit test for frontend
    needs: checks
    defaults:
      run:
        working-directory: ./tests/frontend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: tests/frontend/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm run test-unit

  tests-backend:
    name: run pytest tests
    needs: checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Install pytest
        run: pip install pytest
      - name: Run pytest tests
        run: pytest tests/backend --color=yes

  buid_and_push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    needs:
      - tests-backend
      - tests-unit-frontend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: akorzunin/dwman

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-test:
    runs-on: ubuntu-22.04
    if: ${{ github.ref_name == 'test' }}
    needs:
      - buid_and_push_to_registry
    environment: test
    defaults:
      run:
        working-directory: deploy/test
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: deploy/test
          configuration: |
            [defaults]
            callbacks_enabled = ansible.posix.profile_tasks, ansible.posix.timer
            stdout_callback = yaml
            nocows = false
            interpreter_python = /usr/bin/python
            [ssh_connection]
            retries=5
          vault_password: ${{ secrets.ANSIBLE_PASS }}
          inventory: ${{ vars.ANSIBLE_HOSTS }}
          options: |
            --inventory .hosts
            --limit ${{ vars.SERVER_GROUP }}
            --verbose
            --extra-vars "
            SPOTIPY_CLIENT_ID=${{ secrets.SPOTIPY_CLIENT_ID }}
            SPOTIPY_CLIENT_SECRET=${{ secrets.SPOTIPY_CLIENT_SECRET }}
            SPOTIPY_REDIRECT_URL=${{ vars.SPOTIPY_REDIRECT_URL }}
            MAIL_USERNAME=${{ vars.MAIL_USERNAME }}
            MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
            MAIL_FROM=${{ vars.MAIL_FROM }}
            API_LOGIN=${{ vars.API_LOGIN }}
            API_PASSWORD=${{ vars.API_PASSWORD }}
            PORT=${{ vars.PORT }}
            "
