name: ci-workflow

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  checks:
    name: run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install prettier plugins
        run: npm install -D prettier prettier-plugin-tailwindcss
      - uses: pre-commit/action@v3.0.0

  tests-frontend:
    name: run playwright tests
    needs: checks
    defaults:
      run:
        working-directory: ./tests/frontend
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install project dependencies
        run: npm i
        working-directory: ./src/frontend
      - name: Install Playwright dependencies
        run: npm i
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test-ct

  tests-backend:
    name: run pytest tests
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Install pytest
        run: pip install pytest
      - name: Run pytest tests
        run: pytest tests/backend --color=yes
